[package]
edition = "2018"
name = "next-swc-napi"
version = "0.0.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["rustls-tls"]
# Instead of enabling all the plugin-related features by default, make it explicitly specified
# when build (i.e napi --build --features plugin), same for the wasm as well.
# this is due to some of transitive dependencies have features cannot be enabled at the same time
# (i.e wasmer/default vs wasmer/js-default) while cargo merges all the features at once.
plugin = ["next-binding/__swc_core_binding_napi_plugin", "next-swc/plugin"]
sentry_native_tls = ["_sentry_native_tls"]
sentry_rustls = ["_sentry_rustls"]

native-tls = ["next-binding/__turbo_native_tls"]
rustls-tls = ["next-binding/__turbo_rustls_tls"]

[dependencies]
anyhow = "1.0.66"
backtrace = "0.3"
fxhash = "0.2.1"
napi = { version = "2", default-features = false, features = [
  "napi3",
  "serde-json",
  "tokio_rt",
  "error_anyhow",
] }
napi-derive = "2"
next-swc = { version = "0.0.0", path = "../core" }
once_cell = "1.13.0"
serde = "1"
serde_json = "1"
tracing = { version = "0.1.37", features = ["release_max_level_info"] }
tracing-futures = "0.2.5"
tracing-subscriber = "0.3.9"
tracing-chrome = "0.5.0"
next-binding = { git = "https://github.com/vercel/turbo.git", rev = "079505baf1ce03707d28b6c0afb158dca601a11a", features = [
  "__swc_core_binding_napi",
  "__turbo_next_dev_server",
  "__turbo_node_file_trace",
  "__feature_mdx_rs",
] }

# There are few build targets we can't use native-tls which default features rely on,
# allow to specify alternative (rustls) instead via features.
# Note to opt in rustls default-features should be disabled
# (--no-default-features --features sentry_rustls)
_sentry_native_tls = { package = "sentry", version = "0.27.0", optional = true }
_sentry_rustls = { package = "sentry", version = "0.27.0", default-features = false, features = [
  "backtrace",
  "contexts",
  "panic",
  "rustls",
  "reqwest",
], optional = true }

[build-dependencies]
napi-build = "2"
serde = "1"
serde_json = "1"
